/**
 * Transform Markdown checkboxes into interactive, stateful checkboxes
 * State is saved to localStorage per page
 */
export function initInteractiveCheckboxes() {
  const content = document.querySelector(".mdx-content");
  if (!content) return;

  // Use page URL as unique key for localStorage
  const pageKey = window.location.pathname;
  const savedState = JSON.parse(
    localStorage.getItem(`checklist-${pageKey}`) || "{}",
  );

  // Find all task list items (generated by Markdown from "- [ ]" syntax)
  const taskListItems = content.querySelectorAll("li.task-list-item");

  taskListItems.forEach((li, index) => {
    const checkbox = li.querySelector('input[type="checkbox"]');
    if (!checkbox) return;

    // Enable checkbox (Markdown makes them disabled by default)
    checkbox.removeAttribute("disabled");
    checkbox.classList.add("checklist-checkbox");
    checkbox.id = `checkbox-${index}`;

    // Restore saved state from localStorage
    if (savedState[index] !== undefined) {
      (checkbox as HTMLInputElement).checked = savedState[index];
    }

    // Create label for checkbox text
    // ACCESSIBILITY: Clone li content excluding the checkbox to avoid text duplication
    const liClone = li.cloneNode(true) as HTMLLIElement;
    const checkboxInClone = liClone.querySelector('input[type="checkbox"]');
    checkboxInClone?.remove(); // Remove checkbox from clone to get only the text
    const textContent = liClone.textContent?.trim() || "";

    const label = document.createElement("label");
    label.htmlFor = `checkbox-${index}`;
    label.textContent = textContent;
    label.classList.add("checklist-label");

    // Rebuild list item structure
    li.innerHTML = "";
    li.appendChild(checkbox);
    li.appendChild(label);
    li.classList.remove("task-list-item");
    li.classList.add("checklist-item");

    // Save state to localStorage on change
    checkbox.addEventListener("change", () => {
      const currentState = JSON.parse(
        localStorage.getItem(`checklist-${pageKey}`) || "{}",
      );
      currentState[index] = (checkbox as HTMLInputElement).checked;
      localStorage.setItem(
        `checklist-${pageKey}`,
        JSON.stringify(currentState),
      );
    });
  });
}
